/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as ParsingRouteImport } from './routes/parsing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ApiParseReceiptRouteImport } from './routes/api.parse-receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsingRoute = ParsingRouteImport.update({
  id: '/parsing',
  path: '/parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseReceiptRoute = ApiParseReceiptRouteImport.update({
  id: '/api/parse-receipt',
  path: '/api/parse-receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/claim': typeof ClaimRoute
  '/parsing': typeof ParsingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary': typeof SummaryRoute
  '/api/parse-receipt': typeof ApiParseReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/claim': typeof ClaimRoute
  '/parsing': typeof ParsingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary': typeof SummaryRoute
  '/api/parse-receipt': typeof ApiParseReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/claim': typeof ClaimRoute
  '/parsing': typeof ParsingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary': typeof SummaryRoute
  '/api/parse-receipt': typeof ApiParseReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/claim'
    | '/parsing'
    | '/sitemap.xml'
    | '/summary'
    | '/api/parse-receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/claim'
    | '/parsing'
    | '/sitemap.xml'
    | '/summary'
    | '/api/parse-receipt'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/claim'
    | '/parsing'
    | '/sitemap.xml'
    | '/summary'
    | '/api/parse-receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  ClaimRoute: typeof ClaimRoute
  ParsingRoute: typeof ParsingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SummaryRoute: typeof SummaryRoute
  ApiParseReceiptRoute: typeof ApiParseReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsing': {
      id: '/parsing'
      path: '/parsing'
      fullPath: '/parsing'
      preLoaderRoute: typeof ParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-receipt': {
      id: '/api/parse-receipt'
      path: '/api/parse-receipt'
      fullPath: '/api/parse-receipt'
      preLoaderRoute: typeof ApiParseReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  ClaimRoute: ClaimRoute,
  ParsingRoute: ParsingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SummaryRoute: SummaryRoute,
  ApiParseReceiptRoute: ApiParseReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
